sonar.projectKey=sumer_pathan_enterprise-cicd-ai
sonar.organization=sumer-pathan
sonar.python.version=3.12
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8